{{- $root := . -}}
{{- if .Values.ambassador.filters -}}
{{- range $name, $filter := .Values.ambassador.filters -}}
{{- if $filter.enabled }}
{{- $dnsName := include "common.fullname" $root -}}
{{- if $filterPolicy.dnsNameOverride -}}
{{-   $dnsName = $filterPolicy.dnsNameOverride -}}
{{- end -}}
---
apiVersion: getambassador.io/v3alpha1
kind: Filter
metadata:
  name: ambassador-{{ include "common.fullname" $root }}-{{ $.Release.Namespace }}-okta-sso-filter
  namespace: ambassador
{{- with $filter.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{- with $filter.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  OAuth2:
    accessTokenJWTFilter:
      name: '""'
      namespace: '""'
    audience: api://default
    authorizationURL: https://spoton.okta.com
    clientID: {{ $filter.clientID }}
    clientSessionMaxIdle: 0s
    grantType: '""'
    protectedOrigins:
    - origin: https://{{ $dnsName }}.{{ $.Values.ambassador.tld }}
    secretName: ambassador-oauth2-client-secret
    secretNamespace: ambassador
{{- end -}}
{{- end -}}
{{- end -}}
