{{- $root := . -}}
{{- if .Values.ambassador_tld }}
{{- $ambassador_tld := .Values.ambassador_tld -}}
{{- if .Values.mapping -}}
{{- range $name, $mapping := .Values.mapping -}}
{{- if $mapping.enabled }}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
{{- with $mapping.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{- with $mapping.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  host: {{ $mapping.host }}.{{ $ambassador_tld }}
  prefix: {{ $mapping.prefix | default "/" }}
  grpc: {{ $mapping.grpc | default false }}
  {{- if $mapping.rewrite }}
  rewrite: {{ $mapping.rewrite }}
  {{- end }}
  service: {{ include "common.fullname" $root }}.{{ $root.Release.Namespace }}.svc.cluster.local
  timeout_ms: {{ $mapping.timeout_ms | default 60000 }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
