{{- $root := . -}}
{{- if .Values.ambassador.filterPolicies -}}
{{- range $name, $filterPolicy := .Values.ambassador.filterPolicies -}}
{{- if $filterPolicy.enabled -}}
---
apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: {{ include "common.fullname" $root }}-{{ $name }}
  namespace: ambassador
{{- with $filterPolicy.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{- with $filterPolicy.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  rules:
    {{- range $path := $filterPolicy.excludePaths }}
    - host: {{ include "common.fullname" $root }}.{{ $.Release.Namespace }}.{{ $.Values.ambassador.tld }}
      path: {{ quote $path }}
      filters:
        - name: ambassador-okta-central-filter
          namespace: ambassador
          onDeny: continue
          onAllow: break
        - name: ambassador-{{ include "common.fullname" $root }}-{{ $.Release.Namespace }}-okta-sso-filter
          namespace: ambassador
    {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
