{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "monochart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{- include "common.labels.standard" . | nindent 4 }}
{{- with .Values.serviceAccount.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
{{- end -}}


{{/* Permissions for the service account within given namespace */}}

{{ if ne .Values.serviceAccount.namespacedRules "" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "monochart.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
{{ .Values.serviceAccount.namespacedRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "monochart.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "monochart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "monochart.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}


{{/* Cluster-wide permissions for service account */}}

{{ if ne .Values.serviceAccount.clusterWideRules "" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "monochart.serviceAccountName" . }}-clusterrole
rules:
{{ .Values.serviceAccount.clusterWideRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "monochart.serviceAccountName" . }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ template "monochart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "monochart.serviceAccountName" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{ end }}
