apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "teleport.fullname" . }}-node
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "teleport.name" . }}-node
  template:
    metadata:
      labels:
        app: {{ template "teleport.name" . }}-node
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
{{- if .Values.daemonset.Annotations }}
{{ toYaml .Values.daemonset.Annotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.daemonset.runOnMasters }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Exists"
        effect: "NoSchedule"
    {{- end }}
      hostPID: true
      priorityClassName: system-node-critical
      containers:
      - name: {{ .Chart.Name }}-systemd-installer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/bin/dumb-init"]
        args: ["/bin/bash", "/usr/local/bin/teleport-scripts/install-teleport-systemd.sh"]
        env:
        {{- range $key, $value := .Values.daemonset.extraVars }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
{{- if .Values.license.enabled }}
        - mountPath: {{ .Values.license.mountPath }}
          name: {{ template "teleport.fullname" . }}-license
          readOnly: true
{{- end }}
        - mountPath: /etc/teleport
          name: {{ template "teleport.fullname" . }}-daemonset-config
          readOnly: true
        - mountPath: /usr/local/bin/teleport-scripts
          name: {{ template "teleport.fullname" . }}-bootstrap-scripts
          readOnly: true
        - mountPath: /host/etc/teleport
          name: {{ template "teleport.fullname" . }}-daemonset-host-config
        - mountPath: /etc/systemd/system
          name: {{ template "teleport.fullname" . }}-daemonset-host-etc-systemd-system
        - mountPath: /run
          name: {{ template "teleport.fullname" . }}-daemonset-host-run
        - mountPath: /host/var/lib/teleport
          name: {{ template "teleport.fullname" . }}-daemonset-host-storage
        - mountPath: /sys/fs/cgroup
          name: {{ template "teleport.fullname" . }}-daemonset-host-sys-fs-cgroup
          readOnly: true
        - mountPath: /sys/fs/cgroup/systemd
          name: {{ template "teleport.fullname" . }}-daemonset-host-sys-fs-cgroup-systemd
        - mountPath: /host/usr/local/bin
          name: {{ template "teleport.fullname" . }}-daemonset-host-usr-local-bin
        - mountPath: /var/log/teleport.log
          name: {{ template "teleport.fullname" . }}-daemonset-host-var-log-teleportlog
          readOnly: true
        - mountPath: /var/run/dbus
          name: {{ template "teleport.fullname" . }}-daemonset-host-var-run-dbus
{{- if .Values.daemonset.extraVolumeMounts }}
{{ toYaml .Values.daemonset.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
{{- if .Values.license.enabled }}
      - name: {{ template "teleport.fullname" . }}-license
        secret:
          secretName: {{ .Values.license.secretName }}
{{- end }}
      - name: {{ template "teleport.fullname" . }}-bootstrap-scripts
        configMap:
          name: {{ template "teleport.fullname" . }}-bootstrap-scripts
      - name: {{ template "teleport.fullname" . }}-daemonset-config
        configMap:
          name: {{ template "teleport.fullname" . }}-daemonset-config
      - name: {{ template "teleport.fullname" . }}-daemonset-host-etc-systemd-system
        hostPath:
          path: /etc/systemd/system
          type: Directory
      - name: {{ template "teleport.fullname" . }}-daemonset-host-config
        hostPath:
          path: /etc/teleport
          type: DirectoryOrCreate
      - name: {{ template "teleport.fullname" . }}-daemonset-host-run
        hostPath:
          path: /run
          type: Directory
      - name: {{ template "teleport.fullname" . }}-daemonset-host-sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: {{ template "teleport.fullname" . }}-daemonset-host-sys-fs-cgroup-systemd
        hostPath:
          path: /sys/fs/cgroup/systemd
          type: Directory
      - name: {{ template "teleport.fullname" . }}-daemonset-host-usr-local-bin
        hostPath:
          path: /usr/local/bin
          type: DirectoryOrCreate
      - name: {{ template "teleport.fullname" . }}-daemonset-host-storage
        hostPath:
          path: /var/lib/teleport
          type: DirectoryOrCreate
      - name: {{ template "teleport.fullname" . }}-daemonset-host-var-log-teleportlog
        hostPath:
          path: /var/log/teleport.log
          type: FileOrCreate
      - name: {{ template "teleport.fullname" . }}-daemonset-host-var-run-dbus
        hostPath:
          path: /var/run/dbus
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "teleport.serviceAccountName" . }}
