{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keycloak-gatekeeper.fullname" . }}
  labels: {{ include "keycloak-gatekeeper.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{ include "keycloak-gatekeeper.selector" . | nindent 6 }}
{{- end }}
