{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-gatekeeper.serviceAccountName" . }}
  labels: {{ include "keycloak-gatekeeper.labels" . | nindent 4 }}
{{- end }}
