{{/* Standard secret */}}
{{- if and .Values.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-gatekeeper.fullname" . }}
  labels: {{ include "keycloak-gatekeeper.labels" . | nindent 4 }}
data:
  CLIENT_ID: {{ .Values.ClientID | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.ClientSecret | b64enc | quote }}
{{- if .Values.encryptionKey }}
  ENCRYPTION_KEY: {{ .Values.encryptionKey | b64enc | quote }}
{{- else }}
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- end }}
{{/* Forwarding secret */}}
{{- if and .Values.forwarding.enable .Values.forwarding.generateSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-gatekeeper.fullname" . }}-forwarding
  labels: {{ include "keycloak-gatekeeper.labels" . | nindent 4 }}
data:
  FORWARD_USERNAME: {{ .Values.forwarding.username | b64enc | quote }}
  FORWARD_PASSWORD: {{ .Values.forwarding.password | b64enc | quote }}
{{- end }}
