name: "Validate Catalog Info"

on:
  push:
    paths:
      - '.spoton/**'
  pull_request:
    paths:
      - '.spoton/**'

jobs:
  validate-catalog-info:
    runs-on: [self-hosted, eks-runner, corp, medium] 
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: spotoninc/github-action-validate-catalog-info@main